name: plant_care
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^1.20.1
  cloud_firestore: ^3.4.4
  firebase_auth: ^3.6.3
  firebase_analytics: ^9.3.1
  firebase_storage: ^10.3.5
  firebase_messaging: ^12.0.2

  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  google_sign_in: ^5.4.1
  font_awesome_flutter: ^10.1.0

  one_context: ^2.1.0
  smooth_page_indicator: ^1.0.0+2
  shared_preferences: ^2.0.15



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0



flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/plant_logo.png
  #   - images/a_dot_ham.jpeg

